### ISSUE TITLE
Duplicate forum topic list

### ISSUE THREAD

**Issue by AvidGameFan** [AvidGameFan/dp-display#13] opened 2023-04-13 04:05 UTC
After clicking on a couple of topics, it duplicates the topic list.  It could be related to clicking on the "go to comments" link when I don't have comments loaded.  @Hk1020

**Comment by Hk1020** [comment] 2023-04-13 07:59
That’s weird. I’ve never seen this. The go to comments links directly to the comments section, it doesn’t do anything.

**Comment by Hk1020** [comment] 2023-04-13 08:31
While I do see some not so nice things now I don’t see anything that would lead to duplicate entries. I can’t reproduce. @AvidGameFan do you see any pattern when this happens? Have you loaded the zip file or an individual json?

**Comment by AvidGameFan** [comment] 2023-04-13 13:57
No, I haven't figured out what makes it happen.  Perhaps it's just when I have a local copy?  I'm using the straight .json forum posts file.  It almost feels like a delayed reaction, perhaps part of the screen repainting when you lose focus?  OH, that must be it.  I switch back to the tab, and now I have *4* copies of the topic list!  (That repainting thing may help your mobile situation, but it's adding a delay on the desktop.  In addition to the duplicate list.  There must be a better way to handle the screen refresh!)

**Comment by Hk1020** [comment] 2023-04-13 14:31
Could you check if the problem goes away if you call my page? I’ve put in an ugly fix. This needs a little more work but I don’t have time right now. Will do later if you confirm that my fix works. Also try with the whole zip.

**Comment by AvidGameFan** [comment] 2023-04-17 02:05
I tested it earlier, and I no longer get the duplication, so it seems to work.  I spent a bit of time trying to see if there were an alternative (to the visibilitychange event) to hook into.  In searching, the only other thing I found so far is "requestAnimationFrame()", but I haven't tried that yet.  I don't think that'll work because that is probably only for animation (refreshing 60 frames per second, for example).

OK, I setup my iPhone for testing, and I didn't notice a difference with or without the visibility change except that I get the duplication with the visibilitychange.  In both cases, if I unloaded Safari, I had to start over, loading the forum-posts file.  Just paging around between other tabs or apps, I didn't have to reload anything, and the page was still visible, but I didn't spend a lot of time on it.  Are you sure this is needed for the iPad?  It might be better to have it not do anything unless an iPad is detected.  Or better still, if it could query the DOM and see if the HTML exists?  I can't tell what problem it's fixing.  I guess it's not a big deal, but seems like an interesting problem.

**Comment by Hk1020** [comment] 2023-04-17 10:23
I should have mentioned it, I could reproduce your problem and it should be fixed in #15. It also addresses some other problems.

The root cause for the problem is most likely related to how we (re-)draw the DOM. It is a rather complex problem, I remember from an Angular/React training some time ago that repainting the DOM is not trivial. 

Without reacting to the event I end up with empty pages on switching tabs and I also saw this with Firefox. It is a highly dynamic problem depending on available memory and how it has been used by the browser. Mobile devices kick out applications earlier.

**Closed as completed** 2023-05-01 02:48 UTC
